/**
 * SPDX-License-Identifier: MIT
 *
 * SPDX-FileCopyrightText: 2021 Gaurav Mishra <mishra.gaurav@siemens.com>
 * SPDX-FileCopyrightText: 2025 Kaushlendra Pratap <kaushlendra-pratap.singh@siemens.com>
 * SPDX-FileCopyrightText: 2021 Siemens AG
 */

module.exports = {
  2025: [
    {
      type: "autogenerated",
      dirName: "2025",
    },
  ],
  2024: [
    {
      type: "autogenerated",
      dirName: "2024",
    },
  ],
  2023: [
    {
      type: "autogenerated",
      dirName: "2023",
    },
  ],
  2022: [
    {
      type: "autogenerated",
      dirName: "2022",
    },
  ],
  2021: [
    {
      type: "autogenerated",
      dirName: "2021",
    },
  ],
};
