/**
 * SPDX-License-Identifier: MIT
 *
 * SPDX-FileCopyrightText: 2021 Gaurav Mishra <mishra.gaurav@siemens.com>
 * SPDX-FileCopyrightText: 2021 Siemens AG
 */

module.exports = {
  2022: [
    {
      type: "autogenerated",
      dirName: "2022",
    },
  ],
  2021: [
    {
      type: "autogenerated",
      dirName: "2021",
    },
  ],
};
